# **Question 4: Data Transformation**

##### **Aim**: To transform the Iris dataset into a form suitable for analysis or machine learning. Convert the Species column into numerical indicator columns using one-hot encoding. Standardize the four numerical attributes and display the transformed data to observe how the values have changed.

###### **Experiment reference**: Experiment 2 (cleaning/transformation approach)

In [8]:
# Step 1: Import the required libraries

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [9]:
# Step 2: Load the Iris dataset

iris = pd.read_csv('/content/Iris.csv')
df=pd.DataFrame(iris)
print("Shape of dataset : ",df.shape)
print("\n")
display(df.head())

Shape of dataset :  (150, 6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
# Step 3: Convert the Species column into numerical indicator columns using one-hot encoding

encoded=pd.get_dummies(df, columns=['Species'], dtype=int)
display(encoded.head())

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,1,0,0
1,2,4.9,3.0,1.4,0.2,1,0,0
2,3,4.7,3.2,1.3,0.2,1,0,0
3,4,4.6,3.1,1.5,0.2,1,0,0
4,5,5.0,3.6,1.4,0.2,1,0,0

In [14]:
#Step 4: Standardize the four numerical attributes and display the transformed data to observe how the values have changed

scaler=StandardScaler()
cols = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
encoded[cols] = scaler.fit_transform(encoded[cols])

display(encoded.head())

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,-0.900681,1.019004,-1.340227,-1.315444,1,0,0
1,2,-1.143017,-0.131979,-1.340227,-1.315444,1,0,0
2,3,-1.385353,0.328414,-1.397064,-1.315444,1,0,0
3,4,-1.506521,0.098217,-1.283389,-1.315444,1,0,0
4,5,-1.021849,1.249201,-1.340227,-1.315444,1,0,0

In [18]:
# Step 5: Verify approximate mean 0 and population SD 1

print("Mean of standardized columns :\n")
print(encoded[cols].mean().round(5))

print("Population Standard Deviation :\n")
print(encoded[cols].std(ddof=0))

Mean of standardized columns :

SepalLengthCm    0.0
SepalWidthCm     0.0
PetalLengthCm    0.0
PetalWidthCm     0.0
dtype: float64
Population Standard Deviation :

SepalLengthCm    1.0
SepalWidthCm     1.0
PetalLengthCm    1.0
PetalWidthCm     1.0
dtype: float64