# **Question 10: Linear Regression**

##### **Aim**: To build a Linear Regression model using the Iris dataset to predict PetalLengthCm. Use SepalLengthCm, SepalWidthCm and PetalWidthCm as input features, split the data into training and testing sets, and train the model. Display the model coefficients and predictions for the test data.

###### **Experiment reference**: Experiment 6

In [4]:
# Step 1: Import the required libraries

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [5]:
# Step 2: Load the Iris dataset

iris = pd.read_csv('/content/Iris.csv')
df=pd.DataFrame(iris)
print("Shape of dataset : ",df.shape)
print("\n")
display(df.head())

Shape of dataset :  (150, 6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
#Step 3:  Use SepalLengthCm, SepalWidthCm and PetalWidthCm as input features

features=['SepalLengthCm','SepalWidthCm','PetalWidthCm']
X=df[features]
y=df['PetalLengthCm']

print("Input Features:",X.columns.tolist())
print("Target        :",y.name)

Input Features: ['SepalLengthCm', 'SepalWidthCm', 'PetalWidthCm']
Target        : PetalLengthCm

In [9]:
#Step 4: split the data into training (80%) and testing  (20%) sets

X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

print("training samples:",len(X_train))
print("testing samples :",len(X_test))

training samples: 120
testing samples : 30

In [17]:
#Step 5:  Train the model

model=LinearRegression()
model.fit(X_train,y_train)
print('Training completed\n')

print('Intercept :',model.intercept_)
print()
display(pd.DataFrame({'Features':features, 'Coefficient':model.coef_}))

Training completed

Intercept : -0.2621959025887035

        Features  Coefficient
0  SepalLengthCm     0.722815
1   SepalWidthCm    -0.635816
2   PetalWidthCm     1.467524

In [21]:
# Step 6: Predict and compare with actual values

y_pred=model.predict(X_test)
comparsion=pd.DataFrame({'Actual':y_test.to_numpy(),'Predicted':y_pred})
display(comparsion.head(10))

   Actual  Predicted
0     4.7   4.127716
1     1.7   1.882002
2     6.9   7.025659
3     4.5   4.432110
4     4.8   4.927191
5     1.5   2.066237
6     3.6   3.849479
7     5.1   6.129499
8     4.5   5.021745
9     3.9   3.974453

In [27]:
#Step 7: Evaluate regression performance

MAE=mean_absolute_error(y_test,y_pred)
R_squared=r2_score(y_test,y_pred)

print("Mean Absolute Error :",MAE)
print("R-squared           :",R_squared)
print()
print("Observation: The trained regression model estimates petal length from three other numerical attributes.")

Mean Absolute Error : 0.2605179846252386
R-squared           : 0.9603293155857664

Observation: The trained regression model estimates petal length from three other numerical attributes.