In [8]:
# Step 1 : Import required libs

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as s
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [9]:
# Step 2 : Load the dataset

df=pd.read_csv("/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
# Step 3 : Check its basic info

print("Shape of Dataset :",df.shape)
df.info()

Shape of Dataset : (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [11]:
#step 4 : Display col names and missing values

print(df.columns.tolist())
print(df.isnull().sum())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
# Step 5 : Select relevant features

features=['Pclass','Sex', 'Age', 'SibSp', 'Parch','Fare','Embarked']
data=df[features + ['Survived']].copy()
data.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Survived
0       3    male  22.0      1      0   7.2500        S         0
1       1  female  38.0      1      0  71.2833        C         1
2       3  female  26.0      0      0   7.9250        S         1
3       1  female  35.0      1      0  53.1000        S         1
4       3    male  35.0      0      0   8.0500        S         0

In [13]:
# Step 6 : Handle the missing values (of the data not the df)

data['Age']=data['Age'].fillna(data['Age'].median())
data['Embarked']=data['Embarked'].fillna(data['Embarked'].mode()[0])

print('Missing values after handling :')
print(data.isnull().sum())

Missing values after handling :
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64

In [14]:
# Step 7 : Convert categorical data into numerical form using One Hot Encoding

data=pd.get_dummies(
    data,
    columns=['Sex','Embarked'],
    drop_first=True,
    dtype=int
)
data.head()

,Pclass,Age,SibSp,Parch,Fare,Survived,Sex_male,Embarked_Q,Embarked_S
0,3,22.0,1,0,7.2500,0,1,0,1
1,1,38.0,1,0,71.2833,1,0,0,0
2,3,26.0,0,0,7.9250,1,0,0,1
3,1,35.0,1,0,53.1000,1,0,0,1
4,3,35.0,0,0,8.0500,0,1,0,1

In [15]:
# Step 8 : Separate input features and output

X= data.drop('Survived', axis=1)
y=data['Survived']

print('Input features :')
print(X.columns.tolist())
print('\nTarget: Survived')

Input features :
['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q', 'Embarked_S']

Target: Survived

In [16]:
# Step 9 : Split dataset into training and testing data

# X = features, y = target variable
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training Samples : ",len(X_train))
print("Testing Samples  : ",len(X_test))

Training Samples :  712
Testing Samples  :  179

In [17]:
# Step 10 : Standardize the features (Imp for KNN algo)

scalar=StandardScaler()
X_train_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)

print("Feature Standardization Completed.")

Feature Standardization Completed.

In [18]:
# Step 11 : Create a logistic regression model

log_model=LogisticRegression(max_iter=1000)
print(log_model)

LogisticRegression(max_iter=1000)

In [19]:
# Step 12 : Train logistic regression model

log_model.fit(X_train_scaled,y_train)
print("Logistic Regression Training Completed")

Logistic Regression Training Completed

In [20]:
# Step 13 : Make logistic regression predictions

y_pred_log= log_model.predict(X_test_scaled)
print("First 20 predictions : ")
print(y_pred_log[:20])

First 20 predictions :
[0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1]

In [21]:
# Step 14 : Calculations and validations

# Calculate logistic regression accuracy
accuracy_log=accuracy_score(y_test,y_pred_log)
print("Logistic Regression accuracy : ",accuracy_log)

# Logistic regression confusion matrix
cm_log =confusion_matrix(y_test, y_pred_log)
print(cm_log)

# Logistic regression classification report

print(classification_report(
    y_test,y_pred_log,
    target_names=['Did not Survive','Survived']
))

Logistic Regression accuracy :  0.8044692737430168
[[98 12]
 [23 46]]
                 precision    recall  f1-score   support

Did not Survive       0.81      0.89      0.85       110
       Survived       0.79      0.67      0.72        69

       accuracy                           0.80       179
      macro avg       0.80      0.78      0.79       179
   weighted avg       0.80      0.80      0.80       179

In [23]:
# Step 1 : Create KNN Model

from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
print(knn_model)

KNeighborsClassifier()

In [24]:
# Step 2 : Train KNN Model

knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [25]:
# Step 3 : Make KNN Predictions

y_pred_knn = knn_model.predict(X_test_scaled)
print("First 20 predictions:")
print(y_pred_knn[:20])

First 20 predictions:
[0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1]

In [26]:
# Step 4 : Calculate KNN Accuracy

accuracy_knn = accuracy_score(y_test, y_pred_knn)
print("KNN Accuracy:", accuracy_knn)

KNN Accuracy: 0.8156424581005587

In [28]:
# Step 5 : KNN Confusion Matrix

cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)

[[98 12]
 [21 48]]

In [29]:
# Step 6 : KNN Classification Report

print(classification_report(
    y_test, y_pred_knn,
    target_names=['Did not survive', 'Survived']
))

                 precision    recall  f1-score   support

Did not survive       0.82      0.89      0.86       110
       Survived       0.80      0.70      0.74        69

       accuracy                           0.82       179
      macro avg       0.81      0.79      0.80       179
   weighted avg       0.81      0.82      0.81       179

In [32]:
# Step 7 : Compare Logistic Regression and KNN

comparison = pd.DataFrame({
    'Algorithm': ['Logistic Regression', 'KNN'],
    'Accuracy': [accuracy_log, accuracy_knn]
})
comparison

             Algorithm  Accuracy
0  Logistic Regression  0.804469
1                  KNN  0.815642